strict.perms: false
logging.level: info
logging.to_files: false

filebeat.inputs:
  - type: log
    paths:
      - /usr/share/filebeat/logs/*.ndjson
  - type: mqtt
    enabled: true
    hosts:
      - "mqtt://mqtt:1883"
    username: "ghasensor"
    password: "VeryS3cr3t_P4ssw0rd"
    topics:
      - "ghanode/sensor"
    data_format: plain
    tags: ["mqtt", "ghanode"]
    fields:
      app: ghanode_sensor
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]

setup.ilm.enabled: false
setup.template.enabled: false
